<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="10" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-05T11:00:48 IST" name="Suite" finished-at="2024-07-05T11:01:24 IST" duration-ms="36357">
    <groups>
      <group name="sequential">
        <method signature="Login.ValidatelogIn()[pri:1, instance:testCases.Login@28701274]" name="ValidatelogIn" class="testCases.Login"/>
        <method signature="UnitTestCase.Add_units(java.lang.String,java.lang.String)[pri:3, instance:testCases.UnitTestCase@544fa968]" name="Add_units" class="testCases.UnitTestCase"/>
        <method signature="UnitTestCase.search_units()[pri:4, instance:testCases.UnitTestCase@544fa968]" name="search_units" class="testCases.UnitTestCase"/>
        <method signature="UnitTestCase.deleteUnits()[pri:5, instance:testCases.UnitTestCase@544fa968]" name="deleteUnits" class="testCases.UnitTestCase"/>
      </group> <!-- sequential -->
    </groups>
    <test started-at="2024-07-05T11:00:48 IST" name="Test1" finished-at="2024-07-05T11:01:11 IST" duration-ms="23287">
      <class name="testCases.Login">
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:testCases.Login@28701274]" started-at="2024-07-05T11:00:48 IST" name="beforeTest" finished-at="2024-07-05T11:01:04 IST" duration-ms="15570" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="ValidatelogIn()[pri:1, instance:testCases.Login@28701274]" started-at="2024-07-05T11:01:04 IST" name="ValidatelogIn" finished-at="2024-07-05T11:01:09 IST" duration-ms="5951" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidatelogIn -->
        <test-method retried="true" signature="InvalidlogIn()[pri:2, instance:testCases.Login@28701274]" started-at="2024-07-05T11:01:10 IST" name="InvalidlogIn" finished-at="2024-07-05T11:01:10 IST" duration-ms="217" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.Login.InvalidlogIn(Login.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidlogIn -->
        <test-method retried="true" signature="InvalidlogIn()[pri:2, instance:testCases.Login@28701274]" started-at="2024-07-05T11:01:10 IST" name="InvalidlogIn" finished-at="2024-07-05T11:01:10 IST" duration-ms="386" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.Login.InvalidlogIn(Login.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidlogIn -->
        <test-method signature="InvalidlogIn()[pri:2, instance:testCases.Login@28701274]" started-at="2024-07-05T11:01:10 IST" name="InvalidlogIn" finished-at="2024-07-05T11:01:10 IST" duration-ms="142" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.Login.InvalidlogIn(Login.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidlogIn -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:testCases.Login@28701274]" started-at="2024-07-05T11:01:11 IST" name="afterTest" finished-at="2024-07-05T11:01:11 IST" duration-ms="530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testCases.Login -->
    </test> <!-- Test1 -->
    <test started-at="2024-07-05T11:00:48 IST" name="Test2" finished-at="2024-07-05T11:01:24 IST" duration-ms="36357">
      <class name="testCases.UnitTestCase">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:00:47 IST" name="beforeSuite" finished-at="2024-07-05T11:00:48 IST" duration-ms="583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:00:48 IST" name="beforeTest" finished-at="2024-07-05T11:01:03 IST" duration-ms="14803" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="logIn()[pri:2, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:01:03 IST" name="logIn" finished-at="2024-07-05T11:01:11 IST" duration-ms="7860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method signature="Add_units(java.lang.String,java.lang.String)[pri:3, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:01:11 IST" name="Add_units" data-provider="testdata" finished-at="2024-07-05T11:01:15 IST" duration-ms="4229" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_unit]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[t_unit]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Add_units -->
        <test-method signature="search_units()[pri:4, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:01:15 IST" name="search_units" finished-at="2024-07-05T11:01:18 IST" duration-ms="2954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search_units -->
        <test-method signature="deleteUnits()[pri:5, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:01:18 IST" name="deleteUnits" finished-at="2024-07-05T11:01:24 IST" duration-ms="6027" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUnits -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:01:24 IST" name="afterTest" finished-at="2024-07-05T11:01:24 IST" duration-ms="358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:testCases.UnitTestCase@544fa968]" started-at="2024-07-05T11:01:24 IST" name="afterSuite" finished-at="2024-07-05T11:01:26 IST" duration-ms="1278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testCases.UnitTestCase -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
